### PR TITLE
Add my domains

### PR DESCRIPTION
**Pull request by jfrederickson**
Added my private page.  (Did I get the regex syntax right in root.json?)

### CODE REVIEW

**Comment by MaddieM4** [comment]
Regex syntax looks perfect. I'll test it to make sure it all works correctly - you never know when a stray comma's gonna kill ya.

**Comment by MaddieM4** [comment]
Yup, worked perfectly. Will be up on the public server shortly.

**Comment by jfrederickson** [comment]
Just realized something... I still have an outdated entry for terracrypt.hype in generated.json since it was previously on HypeDNS.  The new one should take precedence, right?

**Comment by MaddieM4** [comment]
@jfrederickson Yep. Private pages always take precedence. The actual mechanics of this are pretty simple - DJDNS scans branch by branch until it finds one that matches the regex. So the branch that points to generated.json sits at the bottom as a catchall.

**Pull request merged**
